// <auto-generated />
using System;
using EfInheritance.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfInheritance.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240712114943_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfInheritance.Domain.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoveringAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policy", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoveringAmount = 5000m,
                            EffectionDate = new DateTime(2024, 7, 12, 15, 19, 42, 927, DateTimeKind.Local).AddTicks(2329),
                            EndDate = new DateTime(2025, 7, 12, 15, 19, 42, 927, DateTimeKind.Local).AddTicks(2337),
                            Title = "Vehicle Thired party inssurance"
                        });
                });

            modelBuilder.Entity("EfInheritance.Domain.Endorsement", b =>
                {
                    b.HasBaseType("EfInheritance.Domain.Policy");

                    b.Property<decimal>("EndorsementCoveringAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndorsementEffectionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndorsementEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndorsementRegsterDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Endorsement", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CoveringAmount = 0m,
                            EffectionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndorsementCoveringAmount = 6000m,
                            EndorsementEffectionDate = new DateTime(2024, 8, 12, 15, 19, 42, 927, DateTimeKind.Local).AddTicks(2459),
                            EndorsementEndDate = new DateTime(2026, 8, 12, 15, 19, 42, 927, DateTimeKind.Local).AddTicks(2456),
                            EndorsementRegsterDate = new DateTime(2024, 7, 12, 15, 19, 42, 927, DateTimeKind.Local).AddTicks(2460)
                        });
                });

            modelBuilder.Entity("EfInheritance.Domain.Endorsement", b =>
                {
                    b.HasOne("EfInheritance.Domain.Policy", null)
                        .WithOne()
                        .HasForeignKey("EfInheritance.Domain.Endorsement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
